language: ruby
services:
  - docker

jobs:
  include:

    - stage: test
      if: branch = develop
      install:
        - bin/docker_build_ci.sh
        - bin/docker_run_ci.sh
      script:
        - docker exec -e RAILS_MASTER_KEY=$RAILS_MASTER_KEY hardtack-ci /bin/sh -c "bundle exec rake test --trace"

    - stage: deploy
      if: branch = master
      install:
        - bin/docker_build.sh
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - docker tag hardtack $DOCKER_USERNAME/hardtack
        - docker push $DOCKER_USERNAME/hardtack
